### PR TITLE
Reconnect proxy if yamux session failed

### LINKED ISSUE #52: Proxy client does not work if yamux connection fails
If an intermediary node is restarted or if a network error happens, the proxy client does not reconnect and stops working. We need to implement reconnection logic.

### PR DESCRIPTION
**Pull request by nkryuchkov**
Fixes #52

Changes:	
- [x] Implement reconnection 
- [x] Adjust broken unit tests for the new implementation

How to test this PR:
Run e2e tests in `skywire-services`.

### CODE REVIEW

File: internal/therealproxy/client.go [hunk 1]
```diff
@@ -16,20 +21,110 @@ var Log = logging.MustGetLogger("therealproxy")
...
+			}
+		}
+	}()
 }
 
-// ListenAndServe start tcp listener on addr and proxies incoming
+// ListenAndServe starts tcp listener on addr and proxies incoming
 // connection to a remote proxy server.
+// TODO: get rid of it
 func (c *Client) ListenAndServe(addr string) error {
```
Comment (Darkren) [inline internal/therealproxy/client.go]: I think we should get rid of this. Since we're passing listener to the client's contructor and have a separate `Serve` func, this `ListenAndServe` makes things confusing

Comment (nkryuchkov) [reply internal/therealproxy/client.go]: @Darkren Good catch. But not sure if it's worth for milestone 1 because the new app is going to be integrated into milestone 2, so the proxy client will require modifications anyway.
